server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    customer-by-address:
      path: /customer-by-address/**
      url: http://localhost:9098
    customer-by-service:
      path: /customer-by-service/**
      serviceId: CUSTOMER-SERVICE
    discovery-by-service:
      path: /hello/**
      serviceId: REST-DISCOVERY-APP1
    rest-discovery-app2: /app2/**
    static:
      path: /static/**

spring:
  application:
    name: zuul-proxy