server:
   port: ${port:8080}
   
spring:
  application:
    name: user-rest-endpoint
  output:
    ansi:
        enabled: DETECT
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

   
    
    
 
  
 
 