server:
   port: ${port:9080}
   
spring:
  application:
    name: camel-context-service
  output:
    ansi:
        enabled: DETECT
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
    
camel:
    springboot:
      name: CamelContextService
    
    
 
  
 
 