server:
   port: ${port:9770}
   
spring:
  application:
    name: zuul-router-app1
  output:
    ansi:
        enabled: DETECT
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
    
    
    
zuul:
  routes:
    hello:
       path: /api/hello/**
       url: http://localhost:9766
    books:
       path: /api/**
       url: http://localhost:9763
 
       
       
 
   
       
 
logging:
  config: /home/abdulg/mywork/microservices/logback-spring.xml
  file: logs/application-debug.log
  pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.netflix: 'WARN'
    org.springframework.cloud: 'WARN'
    org.springframework.web: ERROR
 