server:
   port: ${port:8761}
   
spring:
  application:
    name: eureka-server
  output:
    ansi:
        enabled: DETECT
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
    
    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  
logging:
  file: logs/application-debug.log
  pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.netflix: 'WARN'
    org.springframework.cloud: 'WARN'
    org.springframework.web: ERROR
 